kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  platform:
    channels:
    - name: stable-4.18
      type: ocp
      minVersion: 4.18.23
      maxVersion: 4.18.23
      shortestPath: true
  operators:
  - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.18
    packages:
    - name: odf-dependencies
      channels:
      - name: stable-4.18
    - name: cephcsi-operator
      channels:
      - name: stable-4.18
    - name: ocs-client-operator
      channels:
      - name: stable-4.18
    - name: rook-ceph-operator
      channels:
      - name: stable-4.18
    - name: odf-prometheus-operator
      channels:
      - name: stable-4.18
    - name: odr-cluster-operator
      channels:
      - name: stable-4.18
    - name: odr-hub-operator
      channels:
      - name: stable-4.18
    - name: recipe
      channels:
      - name: stable-4.18
    - name: sriov-network-operator
      channels:
      - name: stable
    - name: odf-operator
      channels:
      - name: stable-4.18
    - name: odf-csi-addons-operator
      channels:
      - name: stable-4.18
    - name: ocs-operator
      channels:
      - name: stable-4.18
    - name: ptp-operator
      channels:
      - name: stable
    - name: local-storage-operator
      channels:
      - name: stable
    - name: mcg-operator
      channels:
      - name: stable-4.18
    - name: lvms-operator
      channels:
      - name: stable-4.18
    - name: kubernetes-nmstate-operator
      channels:
      - name: stable
    - name: cluster-logging
      channels:
      - name: stable-6.4
